# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershopoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersdetail',
            name='costOfService',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
