# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershopoffice', '0002_ordersdetail_costofservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='codeClient',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='nameClient',
        ),
        migrations.RemoveField(
            model_name='ordersdetail',
            name='codeOfService',
        ),
    ]
