# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershopoffice', '0003_auto_20170726_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictclients',
            old_name='nameCleint',
            new_name='nameClient',
        ),
    ]
